---  
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-gluster
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.102.50.61:8080"
  restauthenabled: "true"
  restuser: "admin"
  restuserkey: "Welcome1"
  volumetype: "replicate:2"
allowVolumeExpansion: true   
