---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-loadbalancer
  labels:
    name: nginx-service-loadbalancer
  annotations:
    k8s.co/keepalived-forward-method: DR    
spec:
  type: LoadBalancer
  selector:
    app: nginx-pod  
  ports:
    - name: "http-server-loadbalancer"
      port: 80
      protocol: TCP
